getpelican/pelican-themes

- tuxlite_tbs/templates/base.html
- tuxlite_tbs/templates/tags.html
- tuxlite_tbs/templates/twitter.html
> minor tuxlite_tbs updates

- .gitmodules
Hi, 
I am the author of theme pelican-iliork. Since 10 month ago, it has changed a lot and has a new name. I want to make a pull request to update it. But to ease the review work for you, I am still using the old git url. Hope this will help.
> rename pelican-iliork to chameleon, and update to its lastest commit

- .gitmodules
I have created a minimal theme for single author blogs.
> Add mg theme

- .gitmodules
I've added a theme I modified so that it works with pelican
> added martin pelican theme as submodule

- .gitmodules
You can be interested by my Nest template running there : http://www.molivier.com/
* Featured site header image
* Featured article header image
* Pygments syntax highlighting
* Disqus support for comments
* Google Analytics support
* RSS and Atom feeds
> Added Nest Theme

- simple-bootstrap/static/static/css/style.css
Is this a typo or am I crazy? I searched "css hightlight" on github and got 41k results?
> `hightlight` -> `highlight`

- .gitmodules
You may be interested in *alchemy* https://github.com/nairobilug/pelican-alchemy. Inspired by @porterjamesj's crowsfoot theme. 
Features:
- Disqus support
- Favicon support
- Google analytics support
- Profile image
- Pygments support
- RSS and Atom feeds
- Simple menu
- Social icons
Screenshot:
> Add alchemy theme

- foundation-default-colours/templates/base.html
Hi, 
i made a small modification to this theme. Now pages are linked in the upper menue (was not the case before). Basically line 117-115.
Second change is that the tagcloud will increase the size of the tag, depending on the amount of the mentions.
Thanks,
Hannes
> Link pages in menu for foundation-default-colours theme

- .gitmodules
Pjport is a pelican theme that I use on my personal blog and website. I would like to share my work with other person.
> New pelican theme pjport

- .gitmodules
> Add Flex theme

- dev-random/templates/includes/sidebar.html
Changed Pelican setting identifier from FEED to FEED_ATOM
> Update dev-random theme's FEED to FEED_ATOM

- .gitmodules
Live demo http://samael500.github.io/
> Add W3 Personal Blog theme as submodule

- gum/static/style.css
- gum/templates/sidebar.html
- Change the default ul type to be disc, add margin
- Create a new ul class "blank" to use for the navbar
- Changes are designed to stay in lockstep with how the http://www.gumbyframework.com/docs/#!/introduction website looks
> Gum theme: CSS and template changes to resolve issue #152

- README.rst
Thank you @justinmayer for the link.
> Add a link to a gallery of themes. Fixes #332

- aboutwilson/templates/analytics.html
add GOOGLE_ANALYTICS variable to google analytics script.
> aboutwilson theme: Google Analytics variable fixes #337

- .gitmodules
> Add Hyde theme as submodule

- bricks/templates/article.html
- bricks/templates/article_discus.html
- bricks/templates/base.html
- bricks/templates/trademark.html
Ok, hope to have got this merge stuff straight
> Add Disqus support to Brick theme

- .gitmodules
See: https://github.com/getpelican/pelican-themes/issues/355
> remove ptemplate (defunct)

- .gitmodules
pelican-blue theme URL - https://github.com/Parbhat/pelican-blue
> Add pelican-blue theme as submodule

- .gitmodules
Uberblau is 404ing: https://github.com/uberpartei/uberblau
> Remove Uberblau theme (defunct)

- .gitmodules
pelican-hss URL - https://github.com/laughk/pelican-hss
> Add pelican-hss theme as submodule

- tuxlite_tbs/templates/archives.html
- tuxlite_tbs/templates/article.html
- tuxlite_tbs/templates/base.html
- tuxlite_tbs/templates/category.html
- tuxlite_tbs/templates/page.html
- tuxlite_tbs/templates/sitemap.html
- tuxlite_tbs/templates/tags.html
- Sitemap generator
- Fix page titles
> Further tuxlite_tbs improvements

- .gitmodules
Hello, 
I created a theme that i'm using on my blog http://www.guilhermetoti.com.br
Hope you guys like it! :)
> Add "Nice Blog" theme as submodule

- bootstrap2/templates/base.html
I followed the example of DISPLAY_PAGES_ON_MENU a few lines above.
> bootstrap2: respect DISPLAY_CATEGORIES_ON_MENU setting

- pelican-bootstrap3/static/css/style.css
- pelican-bootstrap3/templates/base.html
Fixed two issues with the CSS. Fixed an issue with anchor tag offsets and fixed an issue with when both the site logo and site name where turned on together.
> pelican-bootstrap3: CSS fixes

- .gitmodules
Also added missing `.git` suffix where necessary.
> Use HTTPS URLs for all git submodules

- pelican-bootstrap3/templates/base.html
1. Use of PAGES instead of pages variable
2. Allow sorting pages alphabetically or otherwise
3. Allow pages without URL.
> pelican-bootstrap3: various improvements

- pelican-bootstrap3/templates/includes/pagination.html
This patch fixes a pagination behavior in conformity with the documentation http://docs.getpelican.com/en/3.6.3/settings.html#using-pagination-patterns
Also fix this issue https://github.com/DandyDev/pelican-bootstrap3/issues/155
> pelican-bootstrap3: fix pagination in the relevant documentation

- pelican-bootstrap3/templates/includes/footer.html
If this happens to be available, i.e. if the article
has a 'modified' date.
> pelican-bootstrap3: Set copyright date to modified date of latest article

- .gitmodules
[It's time for something new.](https://fabianbloggt.de/minimalx-pelican-theme.html) Here's minimalX, making your Pelican-enabled blog enjoyable again.
- Minimal flat design
- Good usability, simple & intuitive navigation
- Focus on what's really important &ndash; your articles. Presented in a clean and straightforward way
- Make tags great again!
- Native integration of media - header images, gallerys, videos
- Fully responsive and mobile-first
- Real tagcloud
- Comments via Disqus integration
- Privacy-friendly social media buttons
- W3.CSS CSS framework & HTML5 semantics
Check out [fabianbloggt.de](http://fabianbloggt.de) for a live demonstration of this theme.
Check the [Wiki](https://github.com/art1fa/minimalX/wiki).
I wrote an [example …
> Add minimalX theme as submodule

- .gitmodules
This theme is the port of [online-cv](https://github.com/sharu725/online-cv) Jekyll theme.
Signed-off-by: Suhaib Khan <suheb.work@gmail.com>
> Add Resume theme as submodule

- .gitmodules
Taman is a port of Jekyll's [Lagom](https://github.com/swanson/lagom) theme
> Add Taman theme as submodule

- Just-Read/less/main.less
- Just-Read/static/css/main.css
- Just-Read/templates/base.html
These changes improve the general readability of code fragments in "Just-Read" on wide screens.
> Just-Read: Various enhancements

- Just-Read/templates/base.html
This is a correction of #558 and is now limited to the `Just Read` Theme.
> Just Read: Extended metadata

- gum/templates/sidebar.html
> Gum: Only show "Categories" sidebar element if there is more than one

- .gitmodules
Adding new theme, created from https://freehtml5.co/preview/?item=marble-free-html5-bootstrap-template-for-portfolio-or-multi-purpose-websites
> Add fh5co-marble theme

- .gitmodules
(port of a pre-existing Wordpress theme)
> Add Grid Focus theme as submodule

- .gitmodules
Designed a new theme inspired by https://brutalist-web.design/
Demo and release notes: https://brutalistpelican.com/
Repo: https://github.com/mamcmanus/brutalist
> Add Brutalist theme as submodule

- notmyidea-cms/templates/twitter.html
I realized that now sharing over twitter doesn't work with article url as messge if we do not use https over http.
Changing url from http to https fixes it.
> notmyidea-cms: Change Twitter link to HTTPS

- pelican-bootstrap3/README.md
It was still not really clear for me, so trying to be as explicit
as possible, see comments to
https://github.com/getpelican/pelican-themes/commit/b30f33e3b7e3a4bc7fb2327e9efd453f3a81488e
> pelican-bootstrap3: Another README improvement for i18n

- Just-Read/templates/article.html
- Just-Read/templates/base.html
This is the second half of b062afff, so that the metadata block is now complete.
> Just Read: Extended metadata block for non-article pages

- gum/templates/sidebar.html
There were category links inside pages.
There was a Pages H4 outside the conditional check for if pages should be shown.
> Gum: Honor conditional categories and pages

- .gitmodules
> pelican_elegant: Link submodule to master branch

- .gitmodules
I am very happy to create this PR to add Buruma theme to `pelican-themes`. This is my first theme. I began to develop it for my personal website, but then I thought that it might be interesting to create it as a theme for everyone. I encourage to you to read the [README](https://github.com/ivanhercaz/buruma) or to visit the [documentation](https://buruma.ivanhercaz.com) (still in progress).
If anyone use this theme or test and have a doubt, find a bug, have a suggestion or whatever, please, feel free to open an issue!
I add Buruma as a submodule, configured to be cloned from the branch `pelican-themes`. This branch will always be updated with latest stable release, not with the master branch, which is the one used to the continuos development. At this moment this branch have Buruma 0.1.0.
> Add Buruma theme

- Peli-Kiera/README.md
- Peli-Kiera/static/css/main.css
- Peli-Kiera/templates/base.html
Theme updated with a few minor changes.
Thanks @justinmayer
> Update Peli-Kiera theme

- Peli-Kiera/static/css/main.css
- Peli-Kiera/templates/analytics.html
- Peli-Kiera/templates/article.html
- Peli-Kiera/templates/base.html
- Peli-Kiera/templates/index.html
Fixes to navbar title line wrapping issue for small screens.
Removed Piwik script.
Thanks!
> Update Peli-Kiera. Fix issue with navbar display. 

- .gitmodules
Resolves #714
Repo for Lab theme no longer exists.
> Remove submodule for Lab theme

- .gitmodules
Hi @justinmayer,
I just finished this theme. I hope that everything is in order.
Thank you!
> Add submodule Papyrus

- .gitmodules
Fixes #723 
Pure Theme is no longer found at the linked repo
> Remove Pure Theme

- .gitmodules
This adds my repository Blue-Penguin-Dark as a submodule. 
Blue-Penguin-Dark adds a dark mode theme with Dark/Light switching via media queries that is mostly true to the original Blue-Penguin theme.
> Add Blue-Penguin-Dark

- .gitmodules
Hi there! 👋️ I've made a new Pelican theme based on [Pico.css](https://github.com/picocss/pico) called [Piccolo](https://github.com/iamjameswalters/piccolo). I'd love to include it here in `pelican-themes`!
> Add Piccolo as submodule

- .github/workflows/build-preview-site.yml
- build-theme-previews.py
* install webassets and cssmin
* emulate i18n_subsites
Should generate previews for a few more themes.
Related: #755 and #754
> Add workarounds to generate previews for some more themes

- graymill/templates/base.html
- graymill/templates/footer.html
Add the footer note variable in the base file
> Add foot note in the graymill theme
