pelican-bootstrap3/EXAMPLES.md
pelican-bootstrap3/README.md
pelican-bootstrap3/templates/base.html
pelican-bootstrap3/templates/includes/coderwall-js.html
pelican-bootstrap3/templates/includes/coderwall.html

I added [coderwall](https://coderwall.com) badges in the sidebar.
An example is here: http://www.higebu.com/

pelican-bootstrap3: Add support for coderwall badges

---

notmyidea-cms/templates/base.html

When `MENUITEMS` it makes the current page active in the menu. The same way it does when the menu is built the default way.

Highlight active menu item in notmyidea-cms theme

---

brownstone/templates/base.html

Add missing `</a>` closing tag for Brownstone

---

brownstone/templates/base.html

Make the class "current_page_item" of the page link in the sidebar shows up only if it's on the current page.
I guess...

fix class "current_page_item" in base.html

---

brownstone/templates/archives.html

The original categories links in the posts in archives.html are wrong, which link to non-existing URLs.

Brownstone: fix wrong categories links in archives.html

---

cebong/static/css/main.css
cebong/templates/article.html
cebong/templates/base.html
cebong/templates/disqus_script.html
cebong/templates/github.html
cebong/templates/piwik.html
cebong/templates/twitter.html

We don't want to have mixed mode on the site, therefore it's useful to use HTTPS wherever possible.
It's no problem to load HTTPS content on a plain HTTP enabled site, but it is a problem the other way round.

Changed a lot of URLs towards HTTPS

---

cebong/templates/archives.html
cebong/templates/article.html
cebong/templates/author.html
cebong/templates/base.html
cebong/templates/category.html
cebong/templates/index.html
cebong/templates/page.html

We want to populate various HTML metatags from pelican. The data is there, we just have to put in HTML!
To be more precise, the meta names "keywords", "category", "description", "author", "robots" and "date" are taken from pelican variables.

Add metadata to Cebong theme

---

new-bootstrap2/templates/sidebar.html

Tagcloud has been moved out to a plugin and is no longer included in the core. This commit checks before generating a tagcloud. Additionally it makes the feed_atom disappear if there's no intent to generate an Atom feed.
Please merge - Thank you!
Pfuender

Fix new-bootstrap2 tagcloud + making feed_atom optional in sidebar

---

tuxlite_tbs/templates/author.html
tuxlite_tbs/templates/categories.html
tuxlite_tbs/templates/tag.html
tuxlite_tbs/templates/twitter.html

Fix previously missed templates that also had the odd <small> tags
Update twitter template to match current twitter docs
When users click twitter button to post link to twitter it should only include the article title, not the site name

More tuxlite_tbs improvements

---

backdrop/README.md

Github has changed the way that you can reference the images. This will
make it so that people going to the repository on github will be able
to see the files.

Backdrop: fix screenshot links in README

---

new-bootstrap2/templates/base.html

new-bootstrap2 doesn't honor the "ARCHIVE_URL" location, this fixes that.

new-bootstrap2: Honor "ARCHIVE_URL" in base template

---

pelican-bootstrap3/templates/base.html
pelican-bootstrap3/templates/page.html

Hi,
I am using the pelican-bootstrap3 theme as a static site, and made two small changes to suite my usage better.
1. As there is no blog on my site, there are no blog archives. The link to empty archives clutters the navigation bar and has no purpose, therefore this commit introduces an option to hide the link. The Readme file has been updated to mention the option.
2. On my static index page I don't set a page title. However, the h1 tag still exists in the HTML. This commit introduces a check for an empty title and, if empty, does not print the h1 tag.
Best,
Clemens

pelican-bootstrap3: hide certain elements if empty

---

.gitmodules

Use 'https' instead of 'git' for the submodule scheme so non-@kura
users can successfully update submodules.

Fix eevee submodule path

---

pelican-bootstrap3/README.md
pelican-bootstrap3/templates/includes/sidebar-images.html

Adds a header above the sidebar images, if any. Live example: http://dmark.github.io/.

pelican-bootstrap3: Add sidebar image header

---

monospace/templates/page.html

The page template in monospace should link against ```{{SITEURL}}/{{page.url}}```, not ```{{SITEURL}}/page.slug}}```. Otherwise the links to the pages that get created won't work (they'll point at /pagename.html instead of /pages/pagename.html).

monospace: link to page.url, not page.slug

---

aboutwilson/templates/base.html

I'm new to pelican and haven't looked into how to do this dynamically with a template variable. Neither `{{ year }}` nor `{{ YEAR }}` seemed to be defined, so here's a commit making the change statically for now.

Fix year in aboutwilson copyright notice

---

pelican-bootstrap3/templates/base.html

jinja searching the wrong variable name (PAGES instead of pages), will fail silently. Fixing the variable name will correctly display pages in the menu for any template inheriting from base.html.

pelican-bootstrap3: Fix outdated PAGES variable to "pages"

---

backdrop/templates/footer.html
backdrop/templates/sample.html
martyalchin/templates/base.html
pelican-bootstrap3/README.md
pelican-bootstrap3/templates/includes/cc-license.html
photowall/templates/base.html

This pull request changes `http://creativecommons.org/...` URLS to `https://creativecommons.org/...` in five templates and one README. It does not make this change in four font-awesome.css files, to maintain consistency with what I assume comes from Font Awesome upstream, or one xmlns attribute.
Full disclosure: the official [CC license chooser](https://creativecommons.org/choose/) produces HTTP URLs even though the HTTPS URLs I tested work.

Use HTTPS Creative Commons URLs where appropriate

---

pelican-bootstrap3/templates/includes/twitter_timeline.html

Also, Widget ID appears to no longer exist anymore on Twitter's end.

Bootstrap3: remove deprecated Twitter widget ID

---

pelican-bootstrap3/EXAMPLES.md

This fixes broken links and adds a new site which uses this template. 
Feedback welcome!

Update example sites for pelican-bootstrap3

---

aboutwilson/templates/base.html

Fixed broken links for categories. Without the fix the URLs result in a 404 status when a category link is clicked.
modified:   aboutwilson/templates/base.html

aboutwilson: Correct theme category links. Fixes #426

---

bootlex/templates/base.html

Added meta tag with charset definition to <head> in base.html template of "bootlex" theme

bootlex: Add UTF-8 meta charset definition

---

pelican-bootstrap3/templates/base.html
pelican-bootstrap3/templates/includes/aboutme.html

The "About Me" block (defined in templates/includes/aboutme.html)
consists of the image defined by AVATAR and the text in ABOUT_ME.
However, the template only displays the block if ABOUT_ME is defined.
If only AVATAR is defined, then the block is not displayed at all.
- Change the test so the "About Me" block is displayed if either
ABOUT_ME or AVATAR is defined.
- Change the structure of the "About Me" block so that the heading for
the ABOUT_ME text is displayed only if ABOUT_ME text is defined,
to avoid an empty heading. If AVATAR is defined but ABOUT_ME is not,
the block displays the AVATAR image only.

pelican-bootstrap3: Fix display of "About Me"

---

pelican-bootstrap3/templates/includes/sidebar.html

The template adds "-square" to the Font Awesome icon to be used,
unless the icon name is on the exception list. Some icon names
potentially relevant for the "social" sidebar block do not have
a "-square" version but are not on the exception list, so the
icons do not display correctly.
Add more relevant icon names to the list: 'home', 'user', 'users',
'envelope', 'envelope-o', 'stack-exchange', 'hacker-news'.

pelican-bootstrap3: Add icons to "social" sidebar

---

pelican-bootstrap3/templates/includes/aboutme.html

When going to a subpage, such as a category page, my avatar image was not
being displayed when using the suggested format 'images/profile.png' from
the readme. The URL turned into 'category/images/profile.png' which doesn't
exist.
Include the site URL so that the image appears on all pages. This looked
like the convention used in other places like favicon.

Fix avatar source URL for subpages in pelican-bootstrap3

---

pelican-bootstrap3/templates/includes/sidebar.html

This hides empty ``li`` tags when you are at either end of an article series. At the moment the empty ``li`` tags are displayed giving some awkward spacing in the sidebar.

pelican-bootstrap3: Hide empty <li> tags when at either end of a series

---

bootstrap2/templates/sidebar.html

Presently, the bootstrap2 sidebar breaks atom feeds, as it doesn't check that the FEED_ALL_ATOM variable is set (in fact, it actually looks for the wrong variable from before the feed refactor).

Fix bootstrap2 atom feed in sidebar

---

tuxlite_tbs/templates/base.html

Saw the issue [here](https://github.com/getpelican/pelican-themes/issues/437) when I was trying to figure out why pages were not showing up for me when I upgraded pelican.

tuxlite_tbs: change PAGES context variable to pages

---

pelican-bootstrap3/README.md

Remove the deprecated `JINJA_EXTENSIONS` indication in favor of the up to date `JINJA_ENVIRONMENT` variable.

fix: pelican-bootstrap3: Update to JINJA_ENVIRONMENT in the README.md

---

pelican-bootstrap3/templates/includes/sidebar/social.html

This commit adds instagram to non-square icon in pelican-bootstrap3
theme to use it.

Add instagram to non-square icon in pelican-bootstrap3

---

.gitmodules

Both pelican-octopress-theme and pelipress seem to have been
abandoned. MrSenko/pelican-octopress-theme is a fork which has
merged all pending PRs from the original repo and also added
the functionality originally developed by pelipress.

Update remotes for octopress and delete pelipress

---

Just-Read/templates/base.html

The pelicanconf.py variable for the ATOM feed is [FEED_ATOM](http://docs.getpelican.com/en/stable/settings.html#feed-settings), not FEED.

Just-Read: Correct FEED_ATOM variable name

---

pelican-bootstrap3/README.md
pelican-bootstrap3/templates/base.html

This enables users of Pelican-Bootstrap3 to link their domain with Flattr, allowing them to recieve Flattrs via the new Flattr plug-in.

Pelican-Bootstrap3: Add support for Flattr domain verification

---

pelican-bootstrap3/README.md

This documents additional configuration required for anybody using the theme with non-English primary sites.

Pelican-Bootstrap3: add I18N language docs clarification

---

pelican-bootstrap3/templates/includes/cc-license.html

See hlapp/cc-tools#3 for the corresponding change in the original source repo.
I recognize this is a minuscule change, but the year 1994 is simply wrong, makes no sense, and is simply an honest mistake.

Fix copyright year to 2014

---

pelican-bootstrap3/templates/includes/sidebar/social.html

This commit adds gitlab to the list of non-square icons in pelican-bootstrap3.

Pelican-Bootstrap3: Add GitLab to non-square icon list

---

SOB/templates/tags.html
ops/templates/category.html
ops/templates/tag.html
ops/templates/tags.html
tuxlite_zf/templates/tags.html
zurb-F5-basic/templates/tags.html

This is to resolve #483
`{% for article in articles | sort %}` resulted in an error in Python 3: 
`"CRITICAL: unorderable types: Article() < Article()"`
I tested with Pelican 3.7.1 in both Python 2.7 & 3.5.

Fix Python 3 unorderable types issue with multiple themes

---

pelican-bootstrap3/templates/includes/twitter_cards.html

As explained on this page, this meta tag prevents Twitter from using your webpage to track people:
https://dev.twitter.com/web/overview/privacy#what-privacy-options-do-website-publishers-have
Generally speaking, this is  the kind of tracking that nobody expects. Nobody thinks that by going to *my* website, which shows some tweets, that Twitter will be tracking them.
Let's turn that off by default. Hopefully this isn't controversial.

pelican-bootstrap3: Add DNT meta so Twitter doesn't track us

---

pelican-bootstrap3/templates/article.html
pelican-bootstrap3/templates/includes/show_source.html
pelican-bootstrap3/templates/includes/sidebar.html
pelican-bootstrap3/templates/includes/sidebar/show_source.html

Update to pelican-boostrap3 to support the [Show Source](https://github.com/getpelican/pelican-plugins/tree/master/show_source) plugin. (Attempt number 2)

pelican-bootstrap3: Add support for Show Source plugin

---

pelican-bootstrap3/README.md
pelican-bootstrap3/templates/base.html
pelican-bootstrap3/templates/includes/sidebar/social.html

If you want to add custom css/js to the theme, without having to clone and maintain your own version of the theme, you can use `CUSTOM_CSS` and `CUSTOM_JS` variables.

pelican-bootstrap3: add CUSTOM_JS var based on CUSTOM_CSS

---

graymill/templates/base.html

Fixes the uppercase 'PAGES' variable (which has now been discontinued).
Pelican made a recent change and now requires lowercase 'pages':
http://docs.getpelican.com/en/stable/faq.html#since-i-upgraded-pelican-my-pages-are-no-longer-rendered

Graymill: Change 'pages' variable to lower-case

---

pelican-bootstrap3/templates/includes/liquid_tags_nb_header.html

It turns out that the theme was using an older version of the mathjax source
src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"
which should be:
src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML"
See news [here](https://www.mathjax.org/cdn-shutting-down/).

Fix link for MathJax source

---

pelican-bootstrap3/EXAMPLES.md
pelican-bootstrap3/README.md
pelican-bootstrap3/templates/base.html

The `PADDED_SINGLE_COLUMN_STYLE` allows the main page content to be
centered with padding on the sides.
This setting takes precidence over `HIDE_SIDEBAR`, `ABOUT_ME`, and
`AVATAR`, hiding the sidebar completely when `PADDED_SINGLE_COLUMN_STYLE`
is set to `True`.
Also cleaned up how the `class`es are assigned in the main content div.
Things were starting to get unreadable in there IMHO.

pelican-bootstrap3: Add PADDED_SINGLE_COLUMN_STYLE setting

---

mnmlist/templates/index.html

Fixes this error:
```
pelican /path/to/blog/content -o /path/to/blog/output -s /path/to/blog/pelicanconf.py 
CRITICAL: UndefinedError: 'loop' is undefined
make: *** [Makefile:65: html] Error 1
```
using the mnmlist theme.
CC: @justinmayer

Fix mnmlist theme`loop` build error

---

.gitmodules

Should fix issue that was breaking the auto-build.

Using HTTPS for Brutalist submodule instead of SSH

---

pelican-bootstrap3/README.md

There are no descriptions of how the various options work, and they don't work in entirely intuitive ways. I've gone through the relevant code and derived what I think are accurate descriptions of what each does.
`GITHUB_SKIP_FORK` especially is confusing, because passing it a boolean will break it.

Updated pelican-bootstrap3 README's Github section

---

pelican-bootstrap3/templates/includes/comments.html

Update the DISQUS "disqus_config" function code style as the example on <https://help.disqus.com/customer/portal/articles/472098-javascript-configuration-variables>.
The "page.identifier" variable always be formatting to "%Y-%m-%d-slug", because an ID conflict may occur while two articles in different categories have the same slug.(<https://help.disqus.com/customer/portal/articles/662547-why-are-the-same-comments-showing-up-on-multiple-pages->) Although article metadata "date" is not mandatory, but it causes an error when it is non-existent, maybe it is used somewhere else.
The "page.url" variable is specified only when "SITEURL" exists( <https://help.disqus.com/customer/portal/articles/472098-javascript-configuration-variables#thispageurl>):
> Please note that an absolute URL is required …

pelican-bootstrap3: Fix Disqus bug #581 

---

uikit/templates/articles.html
zurb-F5-basic/templates/tags.html

This is the issue getpelican/pelican-themes#483 which was supposed to be fixed by #506 (and commit f1a4bba40281fa21816d6619d32136fc6a8f086d), but two occurrences of the problem were missed.
Basically, as https://github.com/getpelican/pelican/issues/1591#issuecomment-70272693 says:
> For future reference: Don't use sort in templates on articles.

Remove two more articles|sort constructs

---

pelican-bootstrap3/templates/base.html

Since Pelican 4.0, `CATEGORY_FEED_ATOM` and `TAG_FEED_ATOM` are expected
to use `{slug}`, not `%s`. Seems to have been introduced in
getpelican/pelican#2383.
This would cause the following error:
```
CRITICAL: TypeError: not all arguments converted during string formatting
```
This change allows for backwards and forward compatibility.

pelican-bootstrap3: Handle Pelican >= 4.0 slugs in feeds

---

gum/templates/base.html

I could not generate a site with the category feeds on.
This was fixed in the simple theme some time ago. Copied the code right from here: 
https://github.com/getpelican/pelican/pull/2515

Gum: Update feeds to new 3.0+ syntax

---

nmnlist/templates/index.html

This issue was fixed with #490 for the `mnmlist` project. However, the issue still existed in the `nmnlist` project. This PR fixes the issue "'loop' is undefined" in the `nmnlist` project now as well.

nmnlist: Fix "loop is undefined" issue

---

cebong/static/css/main.css

It just adds to network roundtrips. Browser will download them even if they are not used. At least the CSS files will be downloaded (and will actually block other processing!). In some case browser will also download actual font files, even if they are not used, but this will usually be done asynchronously or after page is finished loading. But most of the time it is just a waste of bandwidth (but they are cached for 1y and could be used on other websites).
As a bonus I fixed some quotation issues of urls, because this is what I see in css documentation - https://developer.mozilla.org/en-US/docs/Web/CSS/@import
Next improvement would be to move this `@url import` into separate `link` statement in `base.html`, this way things can proceed in parallel more smoothly.
```html
<link …
```

cebong: Removed unused font imports

---

.gitmodules

Bumps up the svbhack submodule to include a version that works with
Pelican 4 and supports the readtime plugin.

Update svbhack with support for Pelican 4 and readtime plugin 

---

pelican-bootstrap3/templates/page.html

… this issue must be handled in the theme.
Strip HTML tags from head title. According to getpelican/pelican#1998 this issue must be handled in the theme.

pelican-bootstrap3: Strip HTML tags from head title

---

.gitmodules

Adds a theme called B-side, which is a port of [Hugo B-side](https://hugo-b-side-demo.netlify.com/). 
Screenshots, documentation, and discussion can be found in the [README](https://github.com/fluffactually/pelican-b-side), and a demo site is available at https://fluffactually.github.io/pelican-b-side-demo/ 
I read a bunch of PRs before submitting this one and couldn't find any official checklist, but here are some things I found which seemed like a good idea and have been implemented:
Let me know if anything needs to be changed or if you have any feedback. Thanks!

Add B-side theme

---

.gitmodules

This PR corrects the submodule link for pelican-b-side, a recently added theme. 
Addresses #683.
To test this fix you may need to update your submodules with `git submodule sync`
Please let me know if you have any feedback on this change or need any additional changes!

Fix broken pelican-b-side submodule link

---

.gitmodules

Stirring: a Pelican theme. 
The theme is used for [hansliu.com](https://hansliu.com) blog.
Fully responsive, customizable for menu, lightbox for the image, cover for the article. Check out [README](https://github.com/hansliu/pelican-stirring/blob/master/README.md) for more information.
Live demo website at [here](https://hansliu.com/pelican-stirring/demo)
**The theme support Pelican 4.5.0**
- Configuration everything as variable as possible.
- Add the latest submodule pelican-stirring as Stirring to the repo.
cc @getpelican, let me know if anything needs to be changed, thanks.

Add Stirring theme as submodule

---

.github/workflows/build-preview-site.yml
.gitignore
.gitmodules
build-theme-previews.py

Added a script for generating theme previews and a actions workflow for publishing the generated preview site under github pages for this repo. I have configured the repo settings. Once this is merged and workflow runs, it should be available under https://getpelican.github.io/pelican-themes . Workflow is configured for pushes on master or manual runs (if necessary).
Example site is currently available at my fork: https://avaris.github.io/pelican-themes/
Heavily based on the work by @maphew, thanks!
Fixes #731, Fixes #740
(kind of... redirection for pelicanthemes.com will be required)

Add preview site build script and GitHub Actions workflow

---

pelican-bootstrap3/README.md
pelican-bootstrap3/templates/includes/sidebar/images.html

Updates the sidebar images feature to allow optional linking of images.
Original purpose of this PR was to add certification marks to the sidebar. This PR adds links so you can optionally add your certification verification links.
refs:
* https://github.com/DandyDev/pelican-bootstrap3/pull/190
* https://github.com/getpelican/pelican-themes/pull/388

Adds optional linking of sidebar images.

---

gum/README.md
gum/templates/base.html
gum/templates/extra_footer.html

This adds a `gum/templates/extra_footer.html` template that is empty by default, so users can add to the footer by putting a file with that name in their template overrides, without forking the theme.

Gum: Add template to allow injecting footer content and markup

---

gum/README.md
gum/templates/base.html

With this change, the `gum` theme can be tweaked for style and behavior without forking it:
1. Create a static css or js file, eg "content/static/foo.css" and "content/static/foo.js" in your site tree.
2. In pelicanconf.py, make sure the directory containing your file is included in `STATIC_PATHS`.
3. Add to pelicanconf.py:
```python
THEME = 'gum'
CUSTOM_CSS_FILES = ['static/foo.css']
CUSTOM_JS_FILES = ['static/foo.js']
```
These will be loaded after the default Gum styles and scripts.
Remotely hosted assets can be supported as well, via `CUSTOM_CSS_URLS` and `CUSTOM_JS_URLS`.
I'm using this on my own website to eg override a few colors and tag cloud text styles:
https://slinkp.com/

Gum: Add optional extra CSS and JS resources
